export const ALL_MENU_ITEMS = [
  "COMPANY", "Profile", "Add Promoter", "View Promoter", "Create Financial Year", "View/Update Financial Year", 
  "Lock Setting", "EOD/BOD", "View Login Details", "Unencumbered Deposit", "Get SMS BALANCE", "Update Content", 
  "System Setting", "Software Config", "SMS Setting Process", "MANAGE MASTER", "Manage Service Tax", "Update Bank Details", 
  "Create State", "View/Update State", "Create District", "View/Update District", "Create News", "View/Update News", 
  "Add IP Address", "View/Update IPAddress", "Create Gallery Category", "Create Gallery", "Manage Popup Screen", 
  "View Recruitment", "MANAGE BRANCH", "Create Branch", "View/Update Branch", "IP Wise Enable/Disable", 
  "Create Service Center", "View Service Center", "Add Service Center User", "View Service Center User", 
  "BANKING MASTER", "Relationship", "Share Parameter", "Fee Parameter", "SB Accounts Parameters", "SB / OD Account Type", 
  "Plan Parameters", "Add Prematurity Slabs", "Approvals Limit parameters", "Service Deduction", "Deposit TDS Parameter", 
  "Add Service Charge", "OD Account Parameters", "Late Fee Parameter", "Holiday List", "HR MODULE", "Designation Master", 
  "Manage Designation", "Designation Menu Rights", "Designation Tree View", "Branch User Rights", "Service Center User Rights", 
  "Training Menu", "Create Employee", "View/manage Employee", "Salary Master", "Employee Attendance Daily", 
  "Create Monthly Attendance", "Create Salary", "Make Payment Salary", "View Monthly Attendance", "View Paid Salary", 
  "Salary Summary Report", "View Staff User", "LOAN", "MANAGE LOAN PRODUCT", "Create Loan SubProduct", "Add Loan Interest Type", 
  "View Loan Interest Type", "Add Collateral Category", "View Loan Product", "Add Document Category", "Add Document List", 
  "Add Processing Fee with slabs", "Loan Calculator", "Interest Calculator", "Create Loan Purpose", "View Loan Purpose", 
  "Delete Loan", "Create Loan Scheme", "View Loan Scheme", "Delete Loan EMI", "Add Charges To Loan", "View Loan Charges Report", 
  "MANAGE OTHER CHARGES", "Add Bouncing Charge", "Add Penalty Charge", "Add OverDue Charge", "CIBIL Score Details", 
  "MANAGE VENDOR", "Add Product Category", "Add Product Vendor", "view Product Vendor", "Vendor Transactions", "Pay To Vendor", 
  "REPORT", "Pending Loans for Approval", "View Approved Loan Accounts", "Dis. Payment Pending Loans", "Bulk Loan Approval", 
  "Disbursement Register", "View Collection Report", "View Rejected Loan Accounts", "View Closed Loan Accounts", 
  "Customer Payment Details", "Loan Balances", "Loan Summary Report", "Foreclosure Loans Waiveoff Request", "Loan Repayment Details", 
  "view co-applicants report", "OverDue", "Vehicle Loan inst Pending Rpt.", "Loan Inst Pending Report", "Provisional Interest", 
  "Demand Sheet", "Progress Report", "Loan Waiveoff Report", "WAITING LOANS REPORT", "Agent Business Report", 
  "Loan Nominee Details", "Loan Part Payment", "Waiveoff Request Report", "Check Cibil Score", "Memberwise Disbursement Rpt.", 
  "EMI Payment Estimation", "View Mortgage Request", "View Mortgage", "CIBIL Report", "Mortgage Closure request", 
  "GROUP LOAN REPORT", "View Group REPORT", "View Group Member", "Active Group Loan", "OverDue Report", "Group Loan Closed", 
  "Group Loan Summary", "GOLD LOAN", "GOLD LOAN MASTER", "MANAGE GOLD RATE", "ADD GOLD SCHEME", "ADD GOLD SCHEME BY AMOUNT", 
  "REPORT", "APPROVAL PENDING LOANS", "REJECTED LOANS", "GL Statement", "Loan Balances", "Approved Gold Loans", 
  "Disbursed Gold Loans", "Closed Gold Loans", "Total EMI Due report", "GL Summary Report", "Gold Loan Delete", 
  "Gold/Mortgage Loan Value Rpt.", "GL Interest Report", "Scheme Wise GL Report", "MANAGE AGENT", "ACCOUNTING", "Group", 
  "Create Group", "View Group", "Ledger", "Create Ledger", "View Ledger", "Profit&Loss Transfer", "Report", "View SubLedger", 
  "SubDay Book", "General Ledger", "CashBook", "BankBook", "Receipt and Payment A/C", "Trial Balance", "Profit and Loss A/C", 
  "Balance Sheet", "GL DayBalance", "Check Balance MisMatch", "Transaction", "Voucher Entry", "UPDATE SHARE DISTINCTIVE", 
  "UPDATE SHARE FOLIO No", "Ledger Change Cash To Bank", "Voucher", "Receipt Voucher", "Payment Voucher", "Journal Voucher", 
  "Cash/Bank To Bank/Cash Transfer", "View Voucher", "Transfer HeadOffice To Branch", "Manage Vendor", "Vendor Enrollment", 
  "View Vendor Enrollment", "CARDS", "Settings", "Create Address", "View Address", "Funding Account", "Set card txn. modes", 
  "User", "Create Card User", "List Of Users", "Card", "Order Card", "List Cards", "view Cards", "Manage Cards", "Transaction", 
  "Transactions List", "View Dispute", "Pool Account Transactions", "PAYMENT GETWAY", "Request For NEFT", "Payment Getway Setup", 
  "NEFT/RTGS/IMPS Setup", "Payment Getway Charges", "Update Virtual Account", "Websoftex Payment SetUp", "Transaction History", 
  "Websoftex Transaction Charges", "REPORTS", "SB", "Deposit & Withdraw Report", "Interest Report", "Opened SB Accounts Report", 
  "Balances Report", "Transaction Report", "SB Monthly Average Balance", "Inactive SB Report", "RD", "RD Planwise Report", 
  "RD Closed Accounts Report", "RD Accounts Matured Today", "RD Interest Report", "FD", "Opening Account Report", 
  "Closed Account Report", "Matured Account Report", "Balance Report", "Pigmy", "Pigmy Planwise Report", "Pigmy Closed Accounts Report", 
  "Pigmy Accounts Matured Today", "Interest Report", "MIS", "MIS Planwise Report", "MIS Closed Accounts Report", 
  "MIS Accounts Matured Today", "MIS Interest Report", "Share", "Share Transaction", "Share Holder Report", "Share Transfer Report", 
  "OD", "Deposit & Withdraw Report", "Opened OD Accounts Report", "Interest Report", "OD Balance", "Closer A/C Report", 
  "Tranaction Report", "Pigmy Withdraw", "PW Balance", "PW Closed", "GENERAL", "Daily Collection report", "Branch Collection Report", 
  "Total Collection report", "Renewal Delete List", "Pending Installment Details", "New Branch Collection Report", "Deleted A/C Report", 
  "Late Fees Report", "Renewal From App", "Share Report", "Maturity Report", "Closed Pre-Maturity Report", "Closed Maturity Report", 
  "Deposit Balance Report", "Pigmy WithDraw Collection RPT", "Agent Ewallet Balance", "NEFT Request Report", 
  "Active/Inactive Accounts History", "REPORTS", "Member Enrollment Report", "Group Enrollment Report", "Transactions Report", 
  "Approve Transactions Report", "SMS Charge Deduct Report", "Member Deposit Report For NDH", "Virtual Account Report", 
  "Corporate Account Statement", "E-Collection Report", "Fund Position Report", "NEFT/IMPS Payment Match From Bank", 
  "Duplicate Member Report", "Collection Alert Status", "Member KYC Status Report", "View Standing Instruction", "BUSINESS REPORT", 
  "TD Maturity Expiry", "NDH-3 Report", "SERVICE CENTER", "Service Center Business", "Member Registration Report", "Service Center Balance", 
  "REQUEST", "Add Balance Request", "Online Request", "Complaint / Help Request", "Feedback / Appreciation Report", 
  "Assign Request To Branch", "Share Transfer Request", "Debit Request Service Center", "View Share Application/Request", 
  "Member Request Enquiry", "Pending Upload Document For Approval", "Verify Member Kyc", "MODIFICATION", "Policy Modification", 
  "Change Nominee", "Change Plan", "Change SB Account Type", "Senior Citizen ROI Change", "Update Member Date", "Deposit Member Change", 
  "Delete Account Transaction", "Delete Accounts", "Block/Un-Block Account", "Deleted Loans Report", "Deleted EMI Report", 
  "Deleted Accounts Report", "Deleted Account Transaction Report", "Update Share date", "Update Member Profile", "TOOLS", 
  "Communication", "Notes", "Manage Calendar", "Manage Events", "Manage Holidays", "Application Summery", "Application Info", 
  "Co Applicant Info", "Upload Document", "PDC & NACH Details", "Bank Account Details", "Existing Loan Details", "Credit Card Details", 
  "Reference Details", "Collateral", "Insurance", "Vehicle Details", "Cibil Verification", "Address Verification", "Doc. Verification", 
  "Print Documents", "Payment Settings", "Add Product Details", "Collateral Verification"
];
